const fs = require('fs');
const path = require('path');

const publicImages = path.resolve(__dirname, '..', 'public', 'images');
const outFile = path.resolve(__dirname, '..', 'src', 'images', 'index.js');

function listFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => !f.startsWith('.'))
    .sort((a,b)=>a.localeCompare(b));
}

const groups = ['featured','row1','row2','capsules'];
const output = [];

groups.forEach(group => {
  const dir = path.join(publicImages, group);
  const files = listFiles(dir).filter(f => /\.(svg|jpe?g|png|webp)$/i.test(f));
  const paths = files.map(f => `/images/${group}/${f}`);
  output.push({ group, paths });
});

const fileContent = `// Auto-generated by scripts/generate_image_index.js
// If you want to manage this file by hand, replace this generator or edit manually.

${output.map(o => `export const ${o.group} = [
${o.paths.map(p => `  '${p}',`).join('\n')}
];`).join('\n\n')}
`;

fs.writeFileSync(outFile, fileContent, 'utf8');
console.log('Wrote', outFile);
